all: dp.c problem1.c problem2.c problem3-1.c problem3-2.c
	gcc dp.c -o dp -pthread
	gcc problem1.c -o problem1 -pthread
	gcc problem2.c -o problem2 -pthread
	gcc problem3-1.c -o problem3-1 -pthread
	gcc problem3-2.c -o problem3-2 -pthread
